image: node:latest

cache:
  paths:
    - node_modules/
stages:
  - deploy

deploy_prod:
  image: ruby:latest
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=poknotes --api-key=$HEROKU_API_KEY
  environment:
    name: "prod"
    url: "https://poknotes.herokuapp.com"
  only:
    - main
  when: manual

deploy_staging:
  image: ruby:latest
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=poknotes-stg --api-key=$HEROKU_API_KEY
  environment:
    name: "staging"
    url: "https://poknotes-stg.herokuapp.com"
  only:
    - main

